
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 05 16:01:02 CST 2013
//----------------------------------------------------

package cnx.syntactic;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int SHR = 45;
  public static final int DIVIDE = 33;
  public static final int SHL = 44;
  public static final int CHAR = 4;
  public static final int GE = 43;
  public static final int STR = 60;
  public static final int ASTER = 32;
  public static final int SUBASS = 54;
  public static final int LPAREN = 16;
  public static final int CONTINUE = 12;
  public static final int MULASS = 50;
  public static final int INT = 5;
  public static final int FOR = 11;
  public static final int MINUS = 31;
  public static final int RPAREN = 17;
  public static final int AND = 39;
  public static final int NOT = 36;
  public static final int SEMICOLON = 18;
  public static final int SIZEOF = 15;
  public static final int TYPEID = 64;
  public static final int SHRASS = 56;
  public static final int LT = 28;
  public static final int ADDASS = 53;
  public static final int OR = 38;
  public static final int ELLIPSIS = 49;
  public static final int COMMA = 19;
  public static final int INC = 46;
  public static final int NUM = 62;
  public static final int TYPEDEF = 2;
  public static final int PLUS = 30;
  public static final int ASSIGN = 20;
  public static final int IF = 8;
  public static final int ID = 63;
  public static final int PTR = 48;
  public static final int DOT = 37;
  public static final int LE = 42;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int error = 1;
  public static final int BITOR = 25;
  public static final int ORASS = 59;
  public static final int MODASS = 52;
  public static final int MOD = 34;
  public static final int ANDASS = 57;
  public static final int BREAK = 13;
  public static final int VOID = 3;
  public static final int EQ = 40;
  public static final int LBRACK = 23;
  public static final int UNION = 7;
  public static final int LBRACE = 21;
  public static final int ELSE = 9;
  public static final int INDEX = 26;
  public static final int RBRACK = 24;
  public static final int WHILE = 10;
  public static final int RBRACE = 22;
  public static final int NE = 41;
  public static final int SHLASS = 55;
  public static final int BITNOT = 35;
  public static final int BITAND = 27;
  public static final int CHR = 61;
  public static final int DEC = 47;
  public static final int DIVASS = 51;
  public static final int STRUCT = 6;
  public static final int GT = 29;
  public static final int XORASS = 58;
}

